/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Envelope,
  EnvelopeString,
  EnvelopeVariantModelsReadVariant,
  EnvelopeVariantModelsReadVariantGroup,
  VariantModelsWriteVariant,
  VariantModelsWriteVariantGroup,
} from '../models';
import {
    EnvelopeFromJSON,
    EnvelopeToJSON,
    EnvelopeStringFromJSON,
    EnvelopeStringToJSON,
    EnvelopeVariantModelsReadVariantFromJSON,
    EnvelopeVariantModelsReadVariantToJSON,
    EnvelopeVariantModelsReadVariantGroupFromJSON,
    EnvelopeVariantModelsReadVariantGroupToJSON,
    VariantModelsWriteVariantFromJSON,
    VariantModelsWriteVariantToJSON,
    VariantModelsWriteVariantGroupFromJSON,
    VariantModelsWriteVariantGroupToJSON,
} from '../models';

export interface AddProductToVariantGroupRequest {
    groupId: number;
    productId: string;
    variant: Array<VariantModelsWriteVariant>;
    productIdType?: AddProductToVariantGroupProductIdTypeEnum;
    include?: string;
}

export interface AddProductToVariantGroupByProductIdRequest {
    productId1: string;
    productId2: string;
    productIdType?: AddProductToVariantGroupByProductIdProductIdTypeEnum;
    include?: string;
}

export interface CreateVariantGroupRequest {
    variantGroup: VariantModelsWriteVariantGroup;
    include?: string;
}

export interface CreateVariantGroupWithProductRequest {
    productId: string;
    variantGroup: VariantModelsWriteVariantGroup;
    productIdType?: CreateVariantGroupWithProductProductIdTypeEnum;
    include?: string;
}

export interface DeleteVariantGroupRequest {
    groupId: number;
}

export interface DeleteVariantGroupByProductIdRequest {
    productId: string;
    productIdType?: DeleteVariantGroupByProductIdProductIdTypeEnum;
}

export interface GetVariantGroupRequest {
    groupId: number;
    include?: string;
}

export interface GetVariantGroupByProductIdRequest {
    productId: string;
    productIdType?: GetVariantGroupByProductIdProductIdTypeEnum;
    include?: string;
}

export interface RemoveProductFromVariantGroupRequest {
    productId: string;
    productIdType?: RemoveProductFromVariantGroupProductIdTypeEnum;
    include?: string;
}

export interface UpdateVariantRequest {
    productId: string;
    variant: Array<VariantModelsWriteVariant>;
    productIdType?: UpdateVariantProductIdTypeEnum;
}

export interface UpdateVariantGroupRequest {
    groupId: number;
    variantGroup: VariantModelsWriteVariantGroup;
    include?: string;
}

/**
 * 
 */
export class VariantApi extends runtime.BaseAPI {

    /**
     * Adds a product to an existing group
     */
    async addProductToVariantGroupRaw(requestParameters: AddProductToVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.groupId === null || requestParameters.groupId === undefined) {
            throw new runtime.RequiredError('groupId','Required parameter requestParameters.groupId was null or undefined when calling addProductToVariantGroup.');
        }

        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling addProductToVariantGroup.');
        }

        if (requestParameters.variant === null || requestParameters.variant === undefined) {
            throw new runtime.RequiredError('variant','Required parameter requestParameters.variant was null or undefined when calling addProductToVariantGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.productIdType !== undefined) {
            queryParameters['productIdType'] = requestParameters.productIdType;
        }

        if (requestParameters.include !== undefined) {
            queryParameters['include'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/VariantGroup/{groupId}/{productId}`.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters.groupId))).replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.variant.map(VariantModelsWriteVariantToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Adds a product to an existing group
     */
    async addProductToVariantGroup(requestParameters: AddProductToVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.addProductToVariantGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a product to an existing group
     */
    async addProductToVariantGroupByProductIdRaw(requestParameters: AddProductToVariantGroupByProductIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.productId1 === null || requestParameters.productId1 === undefined) {
            throw new runtime.RequiredError('productId1','Required parameter requestParameters.productId1 was null or undefined when calling addProductToVariantGroupByProductId.');
        }

        if (requestParameters.productId2 === null || requestParameters.productId2 === undefined) {
            throw new runtime.RequiredError('productId2','Required parameter requestParameters.productId2 was null or undefined when calling addProductToVariantGroupByProductId.');
        }

        const queryParameters: any = {};

        if (requestParameters.productIdType !== undefined) {
            queryParameters['productIdType'] = requestParameters.productIdType;
        }

        if (requestParameters.include !== undefined) {
            queryParameters['include'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/Variant/{productId1}/{productId2}`.replace(`{${"productId1"}}`, encodeURIComponent(String(requestParameters.productId1))).replace(`{${"productId2"}}`, encodeURIComponent(String(requestParameters.productId2))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Adds a product to an existing group
     */
    async addProductToVariantGroupByProductId(requestParameters: AddProductToVariantGroupByProductIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.addProductToVariantGroupByProductIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new variant group
     */
    async createVariantGroupRaw(requestParameters: CreateVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.variantGroup === null || requestParameters.variantGroup === undefined) {
            throw new runtime.RequiredError('variantGroup','Required parameter requestParameters.variantGroup was null or undefined when calling createVariantGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.include !== undefined) {
            queryParameters['include'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/VariantGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VariantModelsWriteVariantGroupToJSON(requestParameters.variantGroup),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Create a new variant group
     */
    async createVariantGroup(requestParameters: CreateVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.createVariantGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new group for the provided product id
     */
    async createVariantGroupWithProductRaw(requestParameters: CreateVariantGroupWithProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling createVariantGroupWithProduct.');
        }

        if (requestParameters.variantGroup === null || requestParameters.variantGroup === undefined) {
            throw new runtime.RequiredError('variantGroup','Required parameter requestParameters.variantGroup was null or undefined when calling createVariantGroupWithProduct.');
        }

        const queryParameters: any = {};

        if (requestParameters.productIdType !== undefined) {
            queryParameters['productIdType'] = requestParameters.productIdType;
        }

        if (requestParameters.include !== undefined) {
            queryParameters['include'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/Variant/{productId}/VariantGroup`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VariantModelsWriteVariantGroupToJSON(requestParameters.variantGroup),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Create a new group for the provided product id
     */
    async createVariantGroupWithProduct(requestParameters: CreateVariantGroupWithProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.createVariantGroupWithProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an entire variant group
     */
    async deleteVariantGroupRaw(requestParameters: DeleteVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.groupId === null || requestParameters.groupId === undefined) {
            throw new runtime.RequiredError('groupId','Required parameter requestParameters.groupId was null or undefined when calling deleteVariantGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/VariantGroup/{groupId}`.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters.groupId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Delete an entire variant group
     */
    async deleteVariantGroup(requestParameters: DeleteVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.deleteVariantGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an entire variant group
     */
    async deleteVariantGroupByProductIdRaw(requestParameters: DeleteVariantGroupByProductIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling deleteVariantGroupByProductId.');
        }

        const queryParameters: any = {};

        if (requestParameters.productIdType !== undefined) {
            queryParameters['productIdType'] = requestParameters.productIdType;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/Variant/{productId}/VariantGroup`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete an entire variant group
     */
    async deleteVariantGroupByProductId(requestParameters: DeleteVariantGroupByProductIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteVariantGroupByProductIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific variant group
     */
    async getVariantGroupRaw(requestParameters: GetVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.groupId === null || requestParameters.groupId === undefined) {
            throw new runtime.RequiredError('groupId','Required parameter requestParameters.groupId was null or undefined when calling getVariantGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.include !== undefined) {
            queryParameters['include'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/VariantGroup/{groupId}`.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters.groupId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Get a specific variant group
     */
    async getVariantGroup(requestParameters: GetVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.getVariantGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the variant group for the provided id
     */
    async getVariantGroupByProductIdRaw(requestParameters: GetVariantGroupByProductIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling getVariantGroupByProductId.');
        }

        const queryParameters: any = {};

        if (requestParameters.productIdType !== undefined) {
            queryParameters['productIdType'] = requestParameters.productIdType;
        }

        if (requestParameters.include !== undefined) {
            queryParameters['include'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/Variant/{productId}/VariantGroup`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Get the variant group for the provided id
     */
    async getVariantGroupByProductId(requestParameters: GetVariantGroupByProductIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.getVariantGroupByProductIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all valid variant labels
     */
    async getVariantLabelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/Variant/Labels`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeStringFromJSON(jsonValue));
    }

    /**
     * Get all valid variant labels
     */
    async getVariantLabels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeString> {
        const response = await this.getVariantLabelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Remove a product from its variant group
     */
    async removeProductFromVariantGroupRaw(requestParameters: RemoveProductFromVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling removeProductFromVariantGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.productIdType !== undefined) {
            queryParameters['productIdType'] = requestParameters.productIdType;
        }

        if (requestParameters.include !== undefined) {
            queryParameters['include'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/Variant/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Remove a product from its variant group
     */
    async removeProductFromVariantGroup(requestParameters: RemoveProductFromVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.removeProductFromVariantGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds the variant details for the product with the provided ID
     */
    async updateVariantRaw(requestParameters: UpdateVariantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariant>> {
        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling updateVariant.');
        }

        if (requestParameters.variant === null || requestParameters.variant === undefined) {
            throw new runtime.RequiredError('variant','Required parameter requestParameters.variant was null or undefined when calling updateVariant.');
        }

        const queryParameters: any = {};

        if (requestParameters.productIdType !== undefined) {
            queryParameters['productIdType'] = requestParameters.productIdType;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/Variant/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.variant.map(VariantModelsWriteVariantToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantFromJSON(jsonValue));
    }

    /**
     * Adds the variant details for the product with the provided ID
     */
    async updateVariant(requestParameters: UpdateVariantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariant> {
        const response = await this.updateVariantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the settings of a group
     */
    async updateVariantGroupRaw(requestParameters: UpdateVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnvelopeVariantModelsReadVariantGroup>> {
        if (requestParameters.groupId === null || requestParameters.groupId === undefined) {
            throw new runtime.RequiredError('groupId','Required parameter requestParameters.groupId was null or undefined when calling updateVariantGroup.');
        }

        if (requestParameters.variantGroup === null || requestParameters.variantGroup === undefined) {
            throw new runtime.RequiredError('variantGroup','Required parameter requestParameters.variantGroup was null or undefined when calling updateVariantGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.include !== undefined) {
            queryParameters['include'] = requestParameters.include;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-apikey"] = this.configuration.apiKey("x-apikey"); // apiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/API/VariantGroup/{groupId}`.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters.groupId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VariantModelsWriteVariantGroupToJSON(requestParameters.variantGroup),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeVariantModelsReadVariantGroupFromJSON(jsonValue));
    }

    /**
     * Updates the settings of a group
     */
    async updateVariantGroup(requestParameters: UpdateVariantGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnvelopeVariantModelsReadVariantGroup> {
        const response = await this.updateVariantGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AddProductToVariantGroupProductIdTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AddProductToVariantGroupProductIdTypeEnum = typeof AddProductToVariantGroupProductIdTypeEnum[keyof typeof AddProductToVariantGroupProductIdTypeEnum];
/**
 * @export
 */
export const AddProductToVariantGroupByProductIdProductIdTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AddProductToVariantGroupByProductIdProductIdTypeEnum = typeof AddProductToVariantGroupByProductIdProductIdTypeEnum[keyof typeof AddProductToVariantGroupByProductIdProductIdTypeEnum];
/**
 * @export
 */
export const CreateVariantGroupWithProductProductIdTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type CreateVariantGroupWithProductProductIdTypeEnum = typeof CreateVariantGroupWithProductProductIdTypeEnum[keyof typeof CreateVariantGroupWithProductProductIdTypeEnum];
/**
 * @export
 */
export const DeleteVariantGroupByProductIdProductIdTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type DeleteVariantGroupByProductIdProductIdTypeEnum = typeof DeleteVariantGroupByProductIdProductIdTypeEnum[keyof typeof DeleteVariantGroupByProductIdProductIdTypeEnum];
/**
 * @export
 */
export const GetVariantGroupByProductIdProductIdTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type GetVariantGroupByProductIdProductIdTypeEnum = typeof GetVariantGroupByProductIdProductIdTypeEnum[keyof typeof GetVariantGroupByProductIdProductIdTypeEnum];
/**
 * @export
 */
export const RemoveProductFromVariantGroupProductIdTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type RemoveProductFromVariantGroupProductIdTypeEnum = typeof RemoveProductFromVariantGroupProductIdTypeEnum[keyof typeof RemoveProductFromVariantGroupProductIdTypeEnum];
/**
 * @export
 */
export const UpdateVariantProductIdTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type UpdateVariantProductIdTypeEnum = typeof UpdateVariantProductIdTypeEnum[keyof typeof UpdateVariantProductIdTypeEnum];
