/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarketModelsMarket
 */
export interface MarketModelsMarket {
    /**
     * 
     * @type {number}
     * @memberof MarketModelsMarket
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MarketModelsMarket
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MarketModelsMarket
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof MarketModelsMarket
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof MarketModelsMarket
     */
    vatRate?: number;
    /**
     * 
     * @type {string}
     * @memberof MarketModelsMarket
     */
    marketPrefix?: string;
    /**
     * 
     * @type {number}
     * @memberof MarketModelsMarket
     */
    countryId?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketModelsMarket
     */
    currencyId?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketModelsMarket
     */
    currencyRate?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketModelsMarket
     */
    languageId?: number;
    /**
     * 
     * @type {string}
     * @memberof MarketModelsMarket
     */
    language?: string;
}

/**
 * Check if a given object implements the MarketModelsMarket interface.
 */
export function instanceOfMarketModelsMarket(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MarketModelsMarketFromJSON(json: any): MarketModelsMarket {
    return MarketModelsMarketFromJSONTyped(json, false);
}

export function MarketModelsMarketFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketModelsMarket {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'displayName': !exists(json, 'DisplayName') ? undefined : json['DisplayName'],
        'currency': !exists(json, 'Currency') ? undefined : json['Currency'],
        'vatRate': !exists(json, 'VatRate') ? undefined : json['VatRate'],
        'marketPrefix': !exists(json, 'MarketPrefix') ? undefined : json['MarketPrefix'],
        'countryId': !exists(json, 'CountryId') ? undefined : json['CountryId'],
        'currencyId': !exists(json, 'CurrencyId') ? undefined : json['CurrencyId'],
        'currencyRate': !exists(json, 'CurrencyRate') ? undefined : json['CurrencyRate'],
        'languageId': !exists(json, 'LanguageId') ? undefined : json['LanguageId'],
        'language': !exists(json, 'Language') ? undefined : json['Language'],
    };
}

export function MarketModelsMarketToJSON(value?: MarketModelsMarket | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'DisplayName': value.displayName,
        'Currency': value.currency,
        'VatRate': value.vatRate,
        'MarketPrefix': value.marketPrefix,
        'CountryId': value.countryId,
        'CurrencyId': value.currencyId,
        'CurrencyRate': value.currencyRate,
        'LanguageId': value.languageId,
        'Language': value.language,
    };
}

