/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Data carrier for a refund
 * @export
 * @interface OrderModelsRefund
 */
export interface OrderModelsRefund {
    /**
     * Unique identifier for this refund
     * @type {number}
     * @memberof OrderModelsRefund
     */
    id?: number;
    /**
     * Reference to the order row that has been refunded
     * @type {number}
     * @memberof OrderModelsRefund
     */
    orderRowId?: number;
    /**
     * Reference to the payment detail that has been refunded
     * @type {number}
     * @memberof OrderModelsRefund
     */
    paymentDetailId?: number;
    /**
     * Id number of the return. Can be used to group refunds.
     * @type {number}
     * @memberof OrderModelsRefund
     */
    returnId?: number;
    /**
     * Article number. If the refund is not bound to an order row this field contains an optional refund article number.
     * @type {string}
     * @memberof OrderModelsRefund
     */
    articleNumber?: string;
    /**
     * Datetime when the refund was created
     * @type {Date}
     * @memberof OrderModelsRefund
     */
    createdAt?: Date;
    /**
     * Total amount refunded
     * @type {number}
     * @memberof OrderModelsRefund
     */
    total?: number;
    /**
     * Reason code for the refund
     * @type {number}
     * @memberof OrderModelsRefund
     */
    reasonCode?: number;
    /**
     * Reason for refund
     * @type {string}
     * @memberof OrderModelsRefund
     */
    reason?: string;
    /**
     * Shows if the refund was deposited to the customers balance
     * @type {boolean}
     * @memberof OrderModelsRefund
     */
    toBalance?: boolean;
    /**
     * Vat percent in decimals for the refunded amount
     * @type {number}
     * @memberof OrderModelsRefund
     */
    vat?: number;
    /**
     * Item ID (SKU).
     * @type {number}
     * @memberof OrderModelsRefund
     */
    itemId?: number;
    /**
     * Refund Type
     * @type {string}
     * @memberof OrderModelsRefund
     */
    refundType?: string;
}

/**
 * Check if a given object implements the OrderModelsRefund interface.
 */
export function instanceOfOrderModelsRefund(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderModelsRefundFromJSON(json: any): OrderModelsRefund {
    return OrderModelsRefundFromJSONTyped(json, false);
}

export function OrderModelsRefundFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderModelsRefund {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'orderRowId': !exists(json, 'OrderRowId') ? undefined : json['OrderRowId'],
        'paymentDetailId': !exists(json, 'PaymentDetailId') ? undefined : json['PaymentDetailId'],
        'returnId': !exists(json, 'ReturnId') ? undefined : json['ReturnId'],
        'articleNumber': !exists(json, 'ArticleNumber') ? undefined : json['ArticleNumber'],
        'createdAt': !exists(json, 'CreatedAt') ? undefined : (new Date(json['CreatedAt'])),
        'total': !exists(json, 'Total') ? undefined : json['Total'],
        'reasonCode': !exists(json, 'ReasonCode') ? undefined : json['ReasonCode'],
        'reason': !exists(json, 'Reason') ? undefined : json['Reason'],
        'toBalance': !exists(json, 'ToBalance') ? undefined : json['ToBalance'],
        'vat': !exists(json, 'Vat') ? undefined : json['Vat'],
        'itemId': !exists(json, 'ItemId') ? undefined : json['ItemId'],
        'refundType': !exists(json, 'RefundType') ? undefined : json['RefundType'],
    };
}

export function OrderModelsRefundToJSON(value?: OrderModelsRefund | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'OrderRowId': value.orderRowId,
        'PaymentDetailId': value.paymentDetailId,
        'ReturnId': value.returnId,
        'ArticleNumber': value.articleNumber,
        'CreatedAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'Total': value.total,
        'ReasonCode': value.reasonCode,
        'Reason': value.reason,
        'ToBalance': value.toBalance,
        'Vat': value.vat,
        'ItemId': value.itemId,
        'RefundType': value.refundType,
    };
}

