/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Contains pagination information for paged operations, i.e. PageSize and PageCount.
 * @export
 * @interface PageResult
 */
export interface PageResult {
    /**
     * The id of the batch operation. If this property has a value for the first fetched page it has to be passed as a parameter for all subsequent requests-
     * @type {string}
     * @memberof PageResult
     */
    batchId?: string;
    /**
     * The current page
     * @type {number}
     * @memberof PageResult
     */
    page?: number;
    /**
     * Total number of rows
     * @type {number}
     * @memberof PageResult
     */
    rowCount?: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PageResult
     */
    pageCount?: number;
    /**
     * Page size
     * @type {number}
     * @memberof PageResult
     */
    pageSize?: number;
    /**
     * True if there is more content to fetch.
     * @type {boolean}
     * @memberof PageResult
     */
    hasMoreRows?: boolean;
}

/**
 * Check if a given object implements the PageResult interface.
 */
export function instanceOfPageResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageResultFromJSON(json: any): PageResult {
    return PageResultFromJSONTyped(json, false);
}

export function PageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'batchId': !exists(json, 'BatchId') ? undefined : json['BatchId'],
        'page': !exists(json, 'Page') ? undefined : json['Page'],
        'rowCount': !exists(json, 'RowCount') ? undefined : json['RowCount'],
        'pageCount': !exists(json, 'PageCount') ? undefined : json['PageCount'],
        'pageSize': !exists(json, 'PageSize') ? undefined : json['PageSize'],
        'hasMoreRows': !exists(json, 'HasMoreRows') ? undefined : json['HasMoreRows'],
    };
}

export function PageResultToJSON(value?: PageResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BatchId': value.batchId,
        'Page': value.page,
        'RowCount': value.rowCount,
        'PageCount': value.pageCount,
        'PageSize': value.pageSize,
        'HasMoreRows': value.hasMoreRows,
    };
}

