/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageAreaModelsReadPageWidget } from './PageAreaModelsReadPageWidget';
import {
    PageAreaModelsReadPageWidgetFromJSON,
    PageAreaModelsReadPageWidgetFromJSONTyped,
    PageAreaModelsReadPageWidgetToJSON,
} from './PageAreaModelsReadPageWidget';

/**
 * This class represents a collection of widgets, and defines how they should be layouted in the area they are rendered in.
 * @export
 * @interface PageAreaModelsReadPageWidgetContainer
 */
export interface PageAreaModelsReadPageWidgetContainer {
    /**
     * The primary ID of this container
     * @type {number}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    id?: number;
    /**
     * The descriptive user defined name of this container, which is used to distinguish this container in a container library
     * @type {string}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    name?: string;
    /**
     * The CSS class names this container should use.
     * @type {Array<string>}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    classNames?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    layout?: string;
    /**
     * 
     * @type {string}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    responsiveMode?: string;
    /**
     * 
     * @type {string}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    visibility?: string;
    /**
     * 
     * @type {string}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    design?: string;
    /**
     * The configured widgets held by this container
     * @type {Array<PageAreaModelsReadPageWidget>}
     * @memberof PageAreaModelsReadPageWidgetContainer
     */
    widgets?: Array<PageAreaModelsReadPageWidget>;
}

/**
 * Check if a given object implements the PageAreaModelsReadPageWidgetContainer interface.
 */
export function instanceOfPageAreaModelsReadPageWidgetContainer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageAreaModelsReadPageWidgetContainerFromJSON(json: any): PageAreaModelsReadPageWidgetContainer {
    return PageAreaModelsReadPageWidgetContainerFromJSONTyped(json, false);
}

export function PageAreaModelsReadPageWidgetContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageAreaModelsReadPageWidgetContainer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'classNames': !exists(json, 'ClassNames') ? undefined : json['ClassNames'],
        'active': !exists(json, 'Active') ? undefined : json['Active'],
        'layout': !exists(json, 'Layout') ? undefined : json['Layout'],
        'responsiveMode': !exists(json, 'ResponsiveMode') ? undefined : json['ResponsiveMode'],
        'visibility': !exists(json, 'Visibility') ? undefined : json['Visibility'],
        'design': !exists(json, 'Design') ? undefined : json['Design'],
        'widgets': !exists(json, 'Widgets') ? undefined : ((json['Widgets'] as Array<any>).map(PageAreaModelsReadPageWidgetFromJSON)),
    };
}

export function PageAreaModelsReadPageWidgetContainerToJSON(value?: PageAreaModelsReadPageWidgetContainer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'ClassNames': value.classNames,
        'Active': value.active,
        'Layout': value.layout,
        'ResponsiveMode': value.responsiveMode,
        'Visibility': value.visibility,
        'Design': value.design,
        'Widgets': value.widgets === undefined ? undefined : ((value.widgets as Array<any>).map(PageAreaModelsReadPageWidgetToJSON)),
    };
}

