/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A canonical product url for a specific market and language.
 * @export
 * @interface ProductModelsReadProductUrl
 */
export interface ProductModelsReadProductUrl {
    /**
     * The canonical url to the product.
     * @type {string}
     * @memberof ProductModelsReadProductUrl
     */
    url?: string;
    /**
     * The market of the url.
     * @type {number}
     * @memberof ProductModelsReadProductUrl
     */
    market?: number;
    /**
     * The language code of the url.
     * @type {string}
     * @memberof ProductModelsReadProductUrl
     */
    language?: string;
}

/**
 * Check if a given object implements the ProductModelsReadProductUrl interface.
 */
export function instanceOfProductModelsReadProductUrl(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductModelsReadProductUrlFromJSON(json: any): ProductModelsReadProductUrl {
    return ProductModelsReadProductUrlFromJSONTyped(json, false);
}

export function ProductModelsReadProductUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductModelsReadProductUrl {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'Url') ? undefined : json['Url'],
        'market': !exists(json, 'Market') ? undefined : json['Market'],
        'language': !exists(json, 'Language') ? undefined : json['Language'],
    };
}

export function ProductModelsReadProductUrlToJSON(value?: ProductModelsReadProductUrl | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Url': value.url,
        'Market': value.market,
        'Language': value.language,
    };
}

