/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SharedModelsLocalizableContent } from './SharedModelsLocalizableContent';
import {
    SharedModelsLocalizableContentFromJSON,
    SharedModelsLocalizableContentFromJSONTyped,
    SharedModelsLocalizableContentToJSON,
} from './SharedModelsLocalizableContent';

/**
 * A product parameter to create or update.
 * @export
 * @interface ProductParameterModelsWriteProductParameter
 */
export interface ProductParameterModelsWriteProductParameter {
    /**
     * The unique identifier for the parameter.
     * @type {number}
     * @memberof ProductParameterModelsWriteProductParameter
     */
    parameterId?: number;
    /**
     * The unique identifier of the group that this parameter belongs to.
     * @type {number}
     * @memberof ProductParameterModelsWriteProductParameter
     */
    groupId?: number;
    /**
     * The type of parameter.
     * @type {number}
     * @memberof ProductParameterModelsWriteProductParameter
     */
    parameterType?: ProductParameterModelsWriteProductParameterParameterTypeEnum;
    /**
     * The non-localized name of the parameter.
     * @type {string}
     * @memberof ProductParameterModelsWriteProductParameter
     */
    name?: string;
    /**
     * The localized names of the parameter.
     * @type {Array<SharedModelsLocalizableContent>}
     * @memberof ProductParameterModelsWriteProductParameter
     */
    localizedNames?: Array<SharedModelsLocalizableContent>;
}


/**
 * @export
 */
export const ProductParameterModelsWriteProductParameterParameterTypeEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7
} as const;
export type ProductParameterModelsWriteProductParameterParameterTypeEnum = typeof ProductParameterModelsWriteProductParameterParameterTypeEnum[keyof typeof ProductParameterModelsWriteProductParameterParameterTypeEnum];


/**
 * Check if a given object implements the ProductParameterModelsWriteProductParameter interface.
 */
export function instanceOfProductParameterModelsWriteProductParameter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductParameterModelsWriteProductParameterFromJSON(json: any): ProductParameterModelsWriteProductParameter {
    return ProductParameterModelsWriteProductParameterFromJSONTyped(json, false);
}

export function ProductParameterModelsWriteProductParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductParameterModelsWriteProductParameter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parameterId': !exists(json, 'ParameterId') ? undefined : json['ParameterId'],
        'groupId': !exists(json, 'GroupId') ? undefined : json['GroupId'],
        'parameterType': !exists(json, 'ParameterType') ? undefined : json['ParameterType'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'localizedNames': !exists(json, 'LocalizedNames') ? undefined : ((json['LocalizedNames'] as Array<any>).map(SharedModelsLocalizableContentFromJSON)),
    };
}

export function ProductParameterModelsWriteProductParameterToJSON(value?: ProductParameterModelsWriteProductParameter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ParameterId': value.parameterId,
        'GroupId': value.groupId,
        'ParameterType': value.parameterType,
        'Name': value.name,
        'LocalizedNames': value.localizedNames === undefined ? undefined : ((value.localizedNames as Array<any>).map(SharedModelsLocalizableContentToJSON)),
    };
}

