/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderCheckoutOrder } from './OrderCheckoutOrder';
import {
    OrderCheckoutOrderFromJSON,
    OrderCheckoutOrderFromJSONTyped,
    OrderCheckoutOrderToJSON,
} from './OrderCheckoutOrder';

/**
 * A query to filter shipping options by.
 * @export
 * @interface ShippingModelsShippingQuery
 */
export interface ShippingModelsShippingQuery {
    /**
     * The site ID the delivery options belong to. Required.
     * @type {number}
     * @memberof ShippingModelsShippingQuery
     */
    siteId?: number;
    /**
     * The country ID where the order should be shipped to.
     * @type {number}
     * @memberof ShippingModelsShippingQuery
     */
    countryId?: number;
    /**
     * Carismar Shipping Option ID
     * @type {number}
     * @memberof ShippingModelsShippingQuery
     */
    shippingId?: number;
    /**
     * Unifaun Delivery Option ID
     * @type {string}
     * @memberof ShippingModelsShippingQuery
     */
    deliveryOptionId?: string;
    /**
     * 
     * @type {OrderCheckoutOrder}
     * @memberof ShippingModelsShippingQuery
     */
    order?: OrderCheckoutOrder;
    /**
     * The cart sum limit for free shipping - to be used for conditions in the delivery checkout portal
     * @type {number}
     * @memberof ShippingModelsShippingQuery
     */
    minimumFreeShippingLimit?: number;
}

/**
 * Check if a given object implements the ShippingModelsShippingQuery interface.
 */
export function instanceOfShippingModelsShippingQuery(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ShippingModelsShippingQueryFromJSON(json: any): ShippingModelsShippingQuery {
    return ShippingModelsShippingQueryFromJSONTyped(json, false);
}

export function ShippingModelsShippingQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingModelsShippingQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'siteId': !exists(json, 'SiteId') ? undefined : json['SiteId'],
        'countryId': !exists(json, 'CountryId') ? undefined : json['CountryId'],
        'shippingId': !exists(json, 'ShippingId') ? undefined : json['ShippingId'],
        'deliveryOptionId': !exists(json, 'DeliveryOptionId') ? undefined : json['DeliveryOptionId'],
        'order': !exists(json, 'Order') ? undefined : OrderCheckoutOrderFromJSON(json['Order']),
        'minimumFreeShippingLimit': !exists(json, 'MinimumFreeShippingLimit') ? undefined : json['MinimumFreeShippingLimit'],
    };
}

export function ShippingModelsShippingQueryToJSON(value?: ShippingModelsShippingQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SiteId': value.siteId,
        'CountryId': value.countryId,
        'ShippingId': value.shippingId,
        'DeliveryOptionId': value.deliveryOptionId,
        'Order': OrderCheckoutOrderToJSON(value.order),
        'MinimumFreeShippingLimit': value.minimumFreeShippingLimit,
    };
}

