/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A product supplier.
 * @export
 * @interface SupplierModelsReadSupplier
 */
export interface SupplierModelsReadSupplier {
    /**
     * The unique identifier for the supplier.
     * @type {number}
     * @memberof SupplierModelsReadSupplier
     */
    supplierId?: number;
    /**
     * The name of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    name?: string;
    /**
     * The first address line of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    address1?: string;
    /**
     * The second address line of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    address2?: string;
    /**
     * The third address line of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    address3?: string;
    /**
     * The zip code of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    zipCode?: string;
    /**
     * The country of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    country?: string;
    /**
     * The contact person of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    contactPerson?: string;
    /**
     * The primary phone number of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    phone1?: string;
    /**
     * The secondary phone number of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    phone2?: string;
    /**
     * The email address of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    email?: string;
    /**
     * External Id of the supplier.
     * @type {string}
     * @memberof SupplierModelsReadSupplier
     */
    externalId?: string;
}

/**
 * Check if a given object implements the SupplierModelsReadSupplier interface.
 */
export function instanceOfSupplierModelsReadSupplier(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SupplierModelsReadSupplierFromJSON(json: any): SupplierModelsReadSupplier {
    return SupplierModelsReadSupplierFromJSONTyped(json, false);
}

export function SupplierModelsReadSupplierFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierModelsReadSupplier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'supplierId': !exists(json, 'SupplierId') ? undefined : json['SupplierId'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'address1': !exists(json, 'Address1') ? undefined : json['Address1'],
        'address2': !exists(json, 'Address2') ? undefined : json['Address2'],
        'address3': !exists(json, 'Address3') ? undefined : json['Address3'],
        'zipCode': !exists(json, 'ZipCode') ? undefined : json['ZipCode'],
        'country': !exists(json, 'Country') ? undefined : json['Country'],
        'contactPerson': !exists(json, 'ContactPerson') ? undefined : json['ContactPerson'],
        'phone1': !exists(json, 'Phone1') ? undefined : json['Phone1'],
        'phone2': !exists(json, 'Phone2') ? undefined : json['Phone2'],
        'email': !exists(json, 'Email') ? undefined : json['Email'],
        'externalId': !exists(json, 'ExternalId') ? undefined : json['ExternalId'],
    };
}

export function SupplierModelsReadSupplierToJSON(value?: SupplierModelsReadSupplier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SupplierId': value.supplierId,
        'Name': value.name,
        'Address1': value.address1,
        'Address2': value.address2,
        'Address3': value.address3,
        'ZipCode': value.zipCode,
        'Country': value.country,
        'ContactPerson': value.contactPerson,
        'Phone1': value.phone1,
        'Phone2': value.phone2,
        'Email': value.email,
        'ExternalId': value.externalId,
    };
}

