/* tslint:disable */
/* eslint-disable */
/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductModelsReadProduct } from './ProductModelsReadProduct';
import {
    ProductModelsReadProductFromJSON,
    ProductModelsReadProductFromJSONTyped,
    ProductModelsReadProductToJSON,
} from './ProductModelsReadProduct';

/**
 * A variant group for a collection of related variants.
 * @export
 * @interface VariantModelsReadVariantGroup
 */
export interface VariantModelsReadVariantGroup {
    /**
     * The id of variant goup.
     * @type {number}
     * @memberof VariantModelsReadVariantGroup
     */
    groupId?: number;
    /**
     * The optional internal name of the variant group.
     * @type {string}
     * @memberof VariantModelsReadVariantGroup
     */
    name?: string;
    /**
     * Determine visibility of non-main products of this group in lists.
     * @type {boolean}
     * @memberof VariantModelsReadVariantGroup
     */
    collapseInLists?: boolean;
    /**
     * The main product of this group. If the group is collapsed in lists, this will be the only visible product.
     * @type {number}
     * @memberof VariantModelsReadVariantGroup
     */
    mainProductId?: number;
    /**
     * The product ids of the variants that belong to this group.
     * @type {Array<number>}
     * @memberof VariantModelsReadVariantGroup
     */
    productIds?: Array<number>;
    /**
     * Products belonging to the Variant group. Only included when parameter "include" is supplied in the query string
     * @type {Array<ProductModelsReadProduct>}
     * @memberof VariantModelsReadVariantGroup
     */
    products?: Array<ProductModelsReadProduct>;
}

/**
 * Check if a given object implements the VariantModelsReadVariantGroup interface.
 */
export function instanceOfVariantModelsReadVariantGroup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VariantModelsReadVariantGroupFromJSON(json: any): VariantModelsReadVariantGroup {
    return VariantModelsReadVariantGroupFromJSONTyped(json, false);
}

export function VariantModelsReadVariantGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariantModelsReadVariantGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': !exists(json, 'GroupId') ? undefined : json['GroupId'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'collapseInLists': !exists(json, 'CollapseInLists') ? undefined : json['CollapseInLists'],
        'mainProductId': !exists(json, 'MainProductId') ? undefined : json['MainProductId'],
        'productIds': !exists(json, 'ProductIds') ? undefined : json['ProductIds'],
        'products': !exists(json, 'Products') ? undefined : ((json['Products'] as Array<any>).map(ProductModelsReadProductFromJSON)),
    };
}

export function VariantModelsReadVariantGroupToJSON(value?: VariantModelsReadVariantGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'GroupId': value.groupId,
        'Name': value.name,
        'CollapseInLists': value.collapseInLists,
        'MainProductId': value.mainProductId,
        'ProductIds': value.productIds,
        'Products': value.products === undefined ? undefined : ((value.products as Array<any>).map(ProductModelsReadProductToJSON)),
    };
}

